[tool.poetry]
name = "fcc-fastapi"
version = "0.1.0"
description = ""
authors = ["Atanas Lambov <alambov@hfmarkets.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
